actiontech/dtle

- internal/logger/text_formatter.go
- scripts/post-install.sh
fix systemctl command can not start dtle
nodeId in log add "nodeid" mark
> fix bug logg nodeId add "nodeId" mark

- internal/client/driver/mysql/extractor.go
> add json check

- Makefile
> add  coverage about kafka

- drivers/mysql/common/taskconfig.go
- drivers/mysql/driver.go
- drivers/mysql/kafka/kafka2.go
- drivers/mysql/kafka/kafka3.go
> Optimize kafka send (fix #518)

- drivers/mysql/common/taskconfig.go
> consider the job as mysql-mysql when kafkaConfig is nil

- drivers/mysql/mysql/binlog/binlog_reader.go
- drivers/mysql/mysql/binlog/binlog_reader_test.go
> support mapping alter table rename

- drivers/mysql/mysql/binlog/binlog_reader.go
> block job if free memory less than 1GiB

- drivers/mysql/mysql/binlog/binlog_reader.go
- drivers/mysql/mysql/binlog/binlog_reader_test.go
> match all tables within the schema if there is no table in the schema's replication config

- drivers/mysql/mysql/binlog/binlog_reader.go
- drivers/mysql/mysql/binlog/binlog_reader_test.go
- drivers/mysql/mysql/extractor.go
> support replicateIgnoreDb

- drivers/api/route/handler.go
- drivers/api/route/route.go
> #157 log level api

- drivers/mysql/common/models.go
- drivers/mysql/handle.go
- drivers/mysql/kafka/kafka3.go
- drivers/mysql/mysql/applier.go
- drivers/mysql/mysql/applier_incr.go
- drivers/mysql/mysql/binlog/binlog_reader.go
- drivers/mysql/mysql/extractor.go
> #608 add tx metrics

- drivers/mysql/mysql/binlog/binlog_reader.go
> skip the dml if the table specified isn't target table

- drivers/mysql/driver.go
- drivers/mysql/mysql/extractor.go
> #558 verify config

- drivers/api/docs/docs.go
- drivers/api/docs/swagger.json
- drivers/api/docs/swagger.yaml
- drivers/api/handler/v2/job.go
- drivers/api/models/base.go
- drivers/api/models/job_v2.go
- drivers/api/route.go
> #636 job list

- drivers/mysql/driver.go
> register handler for "/metrics"

- drivers/api/docs/docs.go
- drivers/api/docs/swagger.json
- drivers/api/docs/swagger.yaml
- drivers/api/handler/common.go
- drivers/api/handler/v2/job.go
- drivers/api/models/job_v2.go
- drivers/api/route.go
- drivers/mysql/common/taskconfig.go
- drivers/mysql/driver.go
- drivers/mysql/handle.go
> #636 get job detail

- drivers/mysql/common/store.go
1.fix job list query bug
2.delete task needs to ensure that the consul data is clean
> fix api bug

- drivers/api/docs/docs.go
- drivers/api/docs/swagger.json
- drivers/api/docs/swagger.yaml
- drivers/api/handler/common.go
- drivers/api/handler/v2/job.go
- drivers/api/models/job_v2.go
1.fix the problem that the job id is misplaced when the interface creates a task
2.fix the problem that replica_ignore_db is incorrectly constructed when creating tasks on the interface
> Api v2 modify

- drivers/api/handler/v2/job.go
- drivers/mysql/mysql/applier.go
- drivers/mysql/mysql/inspect.go
1.the job details do not show nodes that are not running tasks
2.modify the error message of the verification task
> modify job info

- drivers/api/docs/docs.go
- drivers/api/docs/swagger.json
- drivers/api/docs/swagger.yaml
- drivers/api/handler/v2/job.go
- drivers/api/handler/v2/node.go
- drivers/api/handler/v2/validation.go
- drivers/api/models/job_v2.go
- drivers/api/models/node_v2.go
1.api v2/nodes  support get dtle version #777 
2.fix the job details show nodes that are not running tasks
> api v2/nodes  support view dtle version

- drivers/api/docs/docs.go
- drivers/api/docs/swagger.json
- drivers/api/docs/swagger.yaml
- drivers/api/handler/v2/node.go
- drivers/api/models/node_v2.go
1.add  api v2/agent/members 
2.add api v2/status/leader
> support #781

- etc/dtle/nomad.hcl
- Spell Check
- Modify datacenter configuration notes
> modify configuration notes

- drivers/mysql/mysql/oracle/extractor/sql_parse.go
parsing results in DML, some column values have more prefixes(_utf8mb4)
> fix parse dml

- drivers/mysql/mysql/oracle/extractor/log_miner.go
- drivers/mysql/mysql/oracle/extractor/log_miner_test.go
- drivers/mysql/mysql/oracle/extractor/sql_parse.go
- drivers/mysql/mysql/oracle/extractor/sql_parse_test.go
deal with the special characters \ and " in dml
> deal with the special characters \ and " in dml

- drivers/api/docs/docs.go
- drivers/api/docs/swagger.json
- drivers/api/docs/swagger.yaml
- drivers/api/handler/v2/job.go
- drivers/api/models/job_v2.go
feat : api v2 support sqlfilter config
> feat : api v2 support sqlfilter config
